%% CLIMATE ZONES DETAILED TREE
graph TD
    CZD[Climate Zone Details] --> CZD1[Mediterranean Western Cape]
    CZD --> CZD2[Subtropical Eastern Coast]
    CZD --> CZD3[Highland Subtropical Interior]
    CZD --> CZD4[Semi-Arid Karoo]
    CZD --> CZD5[Arid Northern Cape]
    CZD --> CZD6[Coastal Zones]
    
    CZD1 --> CZD1a[Winter Rainfall 400-1500mm]
    CZD1a --> CZD1a1[Fynbos Biome]
    CZD1a1 --> CZD1a1a[Proteaceae Specialists]
    CZD1a1a --> CZD1a1a1[Protea cynaroides - King Protea]
    CZD1a1a --> CZD1a1a2[Leucospermum cordifolium - Pincushion]
    CZD1a1a --> CZD1a1a3[Leucadendron argenteum - Silver Tree]
    CZD1a1 --> CZD1a1b[Ericaceae Family]
    CZD1a1b --> CZD1a1b1[Erica mammosa - Nine-pin Heath]
    CZD1a1b --> CZD1a1b2[Erica verticillata - Whorled Heath]
    CZD1a1 --> CZD1a1c[Restionaceae Family]
    CZD1a1c --> CZD1a1c1[Restio triticeus - Wheat Restio]
    CZD1a1c --> CZD1a1c2[Thamnochortus insignis - Large Restio]
    
    CZD2 --> CZD2a[Summer Rainfall 800-1200mm]
    CZD2a --> CZD2a1[Coastal Forest Species]
    CZD2a1 --> CZD2a1a[Strelitzia nicolai - White Bird of Paradise]
    CZD2a1 --> CZD2a1b[Phoenix reclinata - Wild Date Palm]
    CZD2a1 --> CZD2a1c[Syzygium cordatum - Water Berry]
    CZD2a --> CZD2a2[Grassland Transition]
    CZD2a2 --> CZD2a2a[Clivia miniata - Bush Lily]
    CZD2a2a --> CZD2a2a1[Cultivar: Belgian Hybrids]
    CZD2a2a --> CZD2a2a2[Cultivar: Daruma]
    CZD2a2 --> CZD2a2b[Erythrina lysistemon - Lucky Bean Tree]
    
    CZD3 --> CZD3a[Moderate Rainfall 600-800mm]
    CZD3a --> CZD3a1[Highveld Grassland]
    CZD3a1 --> CZD3a1a[Jacaranda mimosifolia - Jacaranda]
    CZD3a1a --> CZD3a1a1[Standard Purple Form]
    CZD3a1a --> CZD3a1a2[Cultivar: White Christmas]
    CZD3a1 --> CZD3a1b[Olea europaea ssp. africana - Wild Olive]
    CZD3a --> CZD3a2[Urban Adaptable Species]
    CZD3a2 --> CZD3a2a[Buddleja saligna - False Olive]
    CZD3a2 --> CZD3a2b[Celtis africana - White Stinkwood]
    
    CZD4 --> CZD4a[Low Rainfall 200-400mm]
    CZD4a --> CZD4a1[Succulent Karoo]
    CZD4a1 --> CZD4a1a[Aloe dichotoma - Quiver Tree]
    CZD4a1 --> CZD4a1b[Pachypodium namaquanum - Halfmens]
    CZD4a1 --> CZD4a1c[Titanopsis species - Living Granite]
    CZD4a --> CZD4a2[Spiny Shrubs]
    CZD4a2 --> CZD4a2a[Carissa bispinosa - Simple-spine Num-num]
    CZD4a2 --> CZD4a2b[Ehretia rigida - Puzzle Bush]
    
    CZD5 --> CZD5a[Extreme Arid <200mm]
    CZD5a --> CZD5a1[Desert Specialists]
    CZD5a1 --> CZD5a1a[Welwitschia mirabilis - Welwitschia]
    CZD5a1 --> CZD5a1b[Lithops species - Living Stones]
    CZD5a1b --> CZD5a1b1[L. optica - Window Plant]
    CZD5a1b --> CZD5a1b2[L. lesliei - Leslie's Living Stone]
    CZD5a1 --> CZD5a1c[Adromischus species]
    CZD5a1c --> CZD5a1c1[A. cooperi - Plover Eggs Plant]
    CZD5a1c --> CZD5a1c2[A. cristatus - Crinkle-leaf Plant]
    
    CZD6 --> CZD6a[Salt Tolerance Required]
    CZD6a --> CZD6a1[Dune Stabilizers]
    CZD6a1 --> CZD6a1a[Carpobrotus edulis - Sour Fig]
    CZD6a1 --> CZD6a1b[Scaevola taccada - Beach Naupaka]
    CZD6a1 --> CZD6a1c[Tetragonia decumbens - Dune Spinach]
    CZD6a --> CZD6a2[Salt Marsh Species]
    CZD6a2 --> CZD6a2a[Salicornia species - Glasswort]
    CZD6a2 --> CZD6a2b[Limonium species - Sea Lavender]

