%% COMMERCIAL CATEGORIES TREE
graph TD
    CC[Commercial Categories] --> CC1[Indigenous Plants]
    CC --> CC2[Exotic Ornamentals]
    CC --> CC3[Edible Plants]
    CC --> CC4[Medicinal Plants]
    CC --> CC5[Specialty Collections]
    
    CC1 --> CC1a[Fynbos Plants]
    CC1a --> CC1a1[Cut Flower Species]
    CC1a1 --> CC1a1a[Protea cynaroides - King Protea]
    CC1a1 --> CC1a1b[Leucospermum cordifolium - Pincushion]
    CC1a1 --> CC1a1c[Leucadendron species - Cone Bush]
    CC1a --> CC1a2[Garden Specimens]
    CC1a2 --> CC1a2a[Erica species - Heaths]
    CC1a2 --> CC1a2b[Restio species - Cape Reeds]
    CC1a2 --> CC1a2c[Pelargonium species - Wild Geraniums]
    
    CC1 --> CC1b[Water-wise Indigenous]
    CC1b --> CC1b1[Drought Specialists]
    CC1b1 --> CC1b1a[Portulacaria afra - Spekboom]
    CC1b1 --> CC1b1b[Aloe species]
    CC1b1 --> CC1b1c[Crassula species - Jade Plants]
    CC1b --> CC1b2[Coastal Species]
    CC1b2 --> CC1b2a[Carpobrotus edulis - Sour Fig]
    CC1b2 --> CC1b2b[Gazania species - Treasure Flowers]
    
    CC2 --> CC2a[Temperate Ornamentals]
    CC2a --> CC2a1[European Herbs]
    CC2a1 --> CC2a1a[Lavandula angustifolia - English Lavender]
    CC2a1a --> CC2a1a1[Cultivar: Hidcote]
    CC2a1a --> CC2a1a2[Cultivar: Munstead]
    CC2a1 --> CC2a1b[Rosmarinus officinalis - Rosemary]
    CC2a1b --> CC2a1b1[Cultivar: Tuscan Blue]
    CC2a1b --> CC2a1b2[Cultivar: Prostrate]
    CC2a --> CC2a2[Mediterranean Imports]
    CC2a2 --> CC2a2a[Olea europaea - Olive]
    CC2a2a --> CC2a2a1[Cultivar: Frantoio]
    CC2a2a --> CC2a2a2[Cultivar: Mission]
    
    CC2 --> CC2b[Tropical Ornamentals]
    CC2b --> CC2b1[Houseplants]
    CC2b1 --> CC2b1a[Monstera deliciosa - Swiss Cheese Plant]
    CC2b1 --> CC2b1b[Spathiphyllum wallisii - Peace Lily]
    CC2b1 --> CC2b1c[Sansevieria trifasciata - Snake Plant]
    CC2b1c --> CC2b1c1[Cultivar: Laurentii]
    CC2b1c --> CC2b1c2[Cultivar: Hahnii]
    
    CC3 --> CC3a[Herbs & Vegetables]
    CC3a --> CC3a1[Culinary Herbs]
    CC3a1 --> CC3a1a[Origanum vulgare - Oregano]
    CC3a1 --> CC3a1b[Thymus vulgaris - Thyme]
    CC3a1 --> CC3a1c[Petroselinum crispum - Parsley]
    CC3a1c --> CC3a1c1[Flat-leaf Variety]
    CC3a1c --> CC3a1c2[Curly-leaf Variety]
    CC3a --> CC3a2[Indigenous Edibles]
    CC3a2 --> CC3a2a[Carpobrotus edulis - Sour Fig]
    CC3a2 --> CC3a2b[Pelargonium sidoides - African Potato]
    CC3a2 --> CC3a2c[Sutherlandia frutescens - Cancer Bush]
    
    CC3 --> CC3b[Fruit Trees]
    CC3b --> CC3b1[Citrus Species]
    CC3b1 --> CC3b1a[Citrus sinensis - Sweet Orange]
    CC3b1a --> CC3b1a1[Cultivar: Valencia Late]
    CC3b1a --> CC3b1a2[Cultivar: Navel]
    CC3b1 --> CC3b1b[Citrus limon - Lemon]
    CC3b1b --> CC3b1b1[Cultivar: Meyer]
    CC3b1b --> CC3b1b2[Cultivar: Eureka]
    CC3b --> CC3b2[Indigenous Fruits]
    CC3b2 --> CC3b2a[Syzygium cordatum - Water Berry]
    CC3b2 --> CC3b2b[Carissa macrocarpa - Natal Plum]
    
    CC4 --> CC4a[Traditional Medicine]
    CC4a --> CC4a1[Respiratory Ailments]
    CC4a1 --> CC4a1a[Pelargonium sidoides - African Potato]
    CC4a1 --> CC4a1b[Artemisia afra - African Wormwood]
    CC4a --> CC4a2[Immune Support]
    CC4a2 --> CC4a2a[Sutherlandia frutescens - Cancer Bush]
    CC4a2 --> CC4a2b[Hypoxis hemerocallidea - African Star Grass]
    CC4a --> CC4a3[Digestive Health]
    CC4a3 --> CC4a3a[Aloe ferox - Bitter Aloe]
    CC4a3 --> CC4a3b[Centella asiatica - Pennywort]
    
    CC5 --> CC5a[Succulent Collections]
    CC5a --> CC5a1[Rare Specimens]
    CC5a1 --> CC5a1a[Lithops species - Living Stones]
    CC5a1a --> CC5a1a1[L. lesliei - Leslie's Living Stone]
    CC5a1a --> CC5a1a2[L. optica - Window Plant]
    CC5a1 --> CC5a1b[Haworthia species]
    CC5a1b --> CC5a1b1[H. cooperi var. truncata]
    CC5a1b --> CC5a1b2[H. obtusa - Lens Plant]
    CC5a --> CC5a2[Beginner-Friendly]
    CC5a2 --> CC5a2a[Crassula ovata - Jade Plant]
    CC5a2a --> CC5a2a1[Cultivar: Gollum]
    CC5a2a --> CC5a2a2[Cultivar: Hobbit]
    CC5a2 --> CC5a2b[Portulacaria afra - Spekboom]
    
    CC5 --> CC5b[Bonsai Collections]
    CC5b --> CC5b1[Indigenous Bonsai]
    CC5b1 --> CC5b1a[Celtis africana - White Stinkwood]
    CC5b1 --> CC5b1b[Olea europaea ssp. africana - Wild Olive]
    CC5b --> CC5b2[Exotic Bonsai]
    CC5b2 --> CC5b2a[Ficus benjamina - Weeping Fig]
    CC5b2 --> CC5b2b[Serissa foetida - Tree of a Thousand Stars]
