%% CONSERVATION STATUS TREE
graph TD
    CS[Conservation Status] --> CS1[Extinct in Wild]
    CS --> CS2[Critically Endangered]
    CS --> CS3[Endangered]
    CS --> CS4[Vulnerable]
    CS --> CS5[Near Threatened]
    CS --> CS6[Least Concern]
    CS --> CS7[Data Deficient]
    
    CS1 --> CS1a[Nursery Propagation Only]
    CS1a --> CS1a1[Erica verticillata - Whorled Heath]
    CS1a1 --> CS1a1a[Cultivated Population Only]
    CS1a1 --> CS1a1b[Reintroduction Programs]
    
    CS2 --> CS2a[Habitat Loss Specialists]
    CS2a --> CS2a1[Leucadendron argenteum - Silver Tree]
    CS2a1 --> CS2a1a[Peninsula Granite Fynbos Endemic]
    CS2a1 --> CS2a1b[Urban Development Pressure]
    CS2a --> CS2a2[Protea odorata - Sweet Protea]
    CS2a2 --> CS2a2a[Swartland Shale Fynbos]
    CS2a2 --> CS2a2b[Agricultural Conversion]
    
    CS3 --> CS3a[Range-Restricted Species]
    CS3a --> CS3a1[Disa uniflora - Red Disa]
    CS3a1 --> CS3a1a[Table Mountain Seeps]
    CS3a1 --> CS3a1b[Water Table Changes]
    CS3a --> CS3a2[Encephalartos altensteinii - Eastern Cape Cycad]
    CS3a2 --> CS3a2a[Illegal Collection Pressure]
    CS3a2 --> CS3a2b[Habitat Fragmentation]
    
    CS4 --> CS4a[Climate Change Vulnerable]
    CS4a --> CS4a1[Protea magnifica - Queen Protea]
    CS4a1 --> CS4a1a[High Altitude Specialist]
    CS4a1 --> CS4a1b[Temperature Sensitivity]
    CS4a --> CS4a2[Aloe dichotoma - Quiver Tree]
    CS4a2 --> CS4a2a[Rainfall Pattern Changes]
    CS4a2 --> CS4a2b[Karoo Distribution Shifts]
    
    CS5 --> CS5a[Stable but Monitored]
    CS5a --> CS5a1[Protea cynaroides - King Protea]
    CS5a1 --> CS5a1a[Wide Distribution Range]
    CS5a1 --> CS5a1b[Commercial Cultivation Success]
    CS5a --> CS5a2[Strelitzia reginae - Bird of Paradise]
    CS5a2 --> CS5a2a[Garden Escapee Populations]
    CS5a2 --> CS5a2b[Horticultural Value Protection]
    
    CS6 --> CS6a[Common Garden Plants]
    CS6a --> CS6a1[Widely Cultivated]
    CS6a1 --> CS6a1a[Pelargonium x hortorum - Zonal Geranium]
    CS6a1a --> CS6a1a1[Global Distribution]
    CS6a1a --> CS6a1a2[Hybrid Vigor]
    CS6a1 --> CS6a1b[Portulacaria afra - Spekboom]
    CS6a1b --> CS6a1b1[Carbon Sequestration Programs]
    CS6a1b --> CS6a1b2[Restoration Projects]
    
    CS7 --> CS7a[Recently Discovered]
    CS7a --> CS7a1[Remote Location Species]
    CS7a1 --> CS7a1a[Mountain Endemics]
    CS7a1 --> CS7a1b[Desert Specialists]
    CS7a --> CS7a2[Taxonomic Uncertainties]
    CS7a2 --> CS7a2a[Species Complex Groups]
    CS7a2 --> CS7a2b[Hybrid Populations]
