%% ENDEMIC PLANT FAMILIES TREE
graph TD
    EPF[Endemic Plant Families] --> EPF1[Proteaceae]
    EPF --> EPF2[Aizoaceae]
    EPF --> EPF3[Asphodelaceae]
    EPF --> EPF4[Geraniaceae]
    EPF --> EPF5[Ericaceae]
    
    EPF1 --> EPF1a[Protea Genus]
    EPF1a --> EPF1a1[Large Proteas]
    EPF1a1 --> EPF1a1a[P. cynaroides - King Protea]
    EPF1a1a --> EPF1a1a1[Subspecies: cynaroides]
    EPF1a1a --> EPF1a1a2[Cultivar: Little Prince]
    EPF1a1a --> EPF1a1a3[Cultivar: Madiba]
    EPF1a1 --> EPF1a1b[P. magnifica - Queen Protea]
    EPF1a --> EPF1a2[Medium Proteas]
    EPF1a2 --> EPF1a2a[P. repens - Common Sugarbush]
    EPF1a2 --> EPF1a2b[P. neriifolia - Narrow-leaf Sugarbush]
    
    EPF1 --> EPF1b[Leucospermum Genus]
    EPF1b --> EPF1b1[Nodding Pincushions]
    EPF1b1 --> EPF1b1a[L. cordifolium - Heart-leaf Pincushion]
    EPF1b1a --> EPF1b1a1[Cultivar: High Gold]
    EPF1b1a --> EPF1b1a2[Cultivar: Flame Spike]
    EPF1b --> EPF1b2[Upright Pincushions]
    EPF1b2 --> EPF1b2a[L. reflexum - Rocket Pincushion]
    EPF1b2 --> EPF1b2b[L. lineare - Narrow-leaf Pincushion]
    
    EPF1 --> EPF1c[Leucadendron Genus]
    EPF1c --> EPF1c1[Cone Bushes]
    EPF1c1 --> EPF1c1a[L. argenteum - Silver Tree]
    EPF1c1 --> EPF1c1b[L. laureolum - Golden Cone Bush]
    EPF1c1 --> EPF1c1c[L. salignum - Common Cone Bush]
    
    EPF2 --> EPF2a[Mesembryanthemaceae]
    EPF2a --> EPF2a1[Ice Plants]
    EPF2a1 --> EPF2a1a[Lampranthus spectabilis]
    EPF2a1a --> EPF2a1a1[Pink Form]
    EPF2a1a --> EPF2a1a2[Purple Form]
    EPF2a1a --> EPF2a1a3[Orange Form]
    EPF2a1 --> EPF2a1b[Carpobrotus edulis - Sour Fig]
    EPF2a --> EPF2a2[Living Stones]
    EPF2a2 --> EPF2a2a[Lithops lesliei]
    EPF2a2a --> EPF2a2a1[Subspecies: lesliei]
    EPF2a2a --> EPF2a2a2[Subspecies: venteri]
    EPF2a2 --> EPF2a2b[Lithops optica]
    
    EPF3 --> EPF3a[Aloe Genus]
    EPF3a --> EPF3a1[Tree Aloes]
    EPF3a1 --> EPF3a1a[A. barberae - Tree Aloe]
    EPF3a1 --> EPF3a1b[A. dichotoma - Quiver Tree]
    EPF3a --> EPF3a2[Shrub Aloes]
    EPF3a2 --> EPF3a2a[A. ferox - Bitter Aloe]
    EPF3a2 --> EPF3a2b[A. arborescens - Krantz Aloe]
    EPF3a --> EPF3a3[Grass Aloes]
    EPF3a3 --> EPF3a3a[A. striata - Coral Aloe]
    EPF3a3 --> EPF3a3b[A. brevifolia - Short-leaf Aloe]
    
    EPF4 --> EPF4a[Pelargonium Genus]
    EPF4a --> EPF4a1[Scented-leaf Species]
    EPF4a1 --> EPF4a1a[P. graveolens - Rose Geranium]
    EPF4a1 --> EPF4a1b[P. tomentosum - Peppermint Geranium]
    EPF4a1 --> EPF4a1c[P. citronellum - Citronella Geranium]
    EPF4a --> EPF4a2[Flowering Species]
    EPF4a2 --> EPF4a2a[P. peltatum - Ivy Geranium]
    EPF4a2a --> EPF4a2a1[Cultivar: Cascade Series]
    EPF4a2a --> EPF4a2a2[Cultivar: Summer Showers]
    EPF4a2 --> EPF4a2b[P. x hortorum - Zonal Geranium]
    
    EPF5 --> EPF5a[Erica Genus]
    EPF5a --> EPF5a1[Tall Heaths]
    EPF5a1 --> EPF5a1a[E. mammosa - Nine-pin Heath]
    EPF5a1 --> EPF5a1b[E. verticillata - Whorled Heath]
    EPF5a --> EPF5a2[Compact Heaths]
    EPF5a2 --> EPF5a2a[E. baccans - Berry Heath]
    EPF5a2 --> EPF5a2b[E. grandiflora - Large-flowered Heath]
