%% SEASONAL PATTERNS TREE
graph TD
    SP[Seasonal Patterns] --> SP1[Summer Growing Season]
    SP --> SP2[Winter Growing Season]
    SP --> SP3[Year-Round Growing]
    
    SP1 --> SP1a[October-March Active]
    SP1a --> SP1a1[Summer Rainfall Species]
    SP1a1 --> SP1a1a[Aloe ferox - Bitter Aloe]
    SP1a1 --> SP1a1b[Strelitzia reginae - Bird of Paradise]
    SP1a1 --> SP1a1c[Clivia miniata - Bush Lily]
    SP1a1c --> SP1a1c1[Cultivar: Belgian Hybrids]
    SP1a1c --> SP1a1c2[Cultivar: Daruma]
    SP1a1c --> SP1a1c3[Cultivar: Yellow Lady]
    
    SP2 --> SP2a[May-September Active]
    SP2a --> SP2a1[Winter Rainfall Species]
    SP2a1 --> SP2a1a[Protea cynaroides - King Protea]
    SP2a1a --> SP2a1a1[Cultivar: Little Prince]
    SP2a1a --> SP2a1a2[Cultivar: Madiba]
    SP2a1a --> SP2a1a3[Cultivar: Mini King]
    SP2a1 --> SP2a1b[Leucadendron argenteum - Silver Tree]
    SP2a1 --> SP2a1c[Erica species - Heaths]
    SP2a1c --> SP2a1c1[Erica verticillata - Whorled Heath]
    SP2a1c --> SP2a1c2[Erica mammosa - Nine-pin Heath]
    SP2a1c --> SP2a1c3[Erica baccans - Berry Heath]
    
    SP3 --> SP3a[Minimal Seasonality]
    SP3a --> SP3a1[Succulent Species]
    SP3a1 --> SP3a1a[Portulacaria afra - Spekboom]
    SP3a1a --> SP3a1a1[Variegated Form]
    SP3a1a --> SP3a1a2[Prostrate Form]
    SP3a1 --> SP3a1b[Lithops species - Living Stones]
    SP3a1b --> SP3a1b1[L. lesliei subspecies]
    SP3a1b --> SP3a1b2[L. optica subspecies]
    SP3a1 --> SP3a1c[Haworthia species]
    SP3a1c --> SP3a1c1[H. cooperi var. truncata]
    SP3a1c --> SP3a1c2[H. attenuata - Zebra Plant]
